export const LABEL_VARIABLES = [
  { value: "${etiqueta.areaVenda}", label: "Área de Venda" },
  { value: "${etiqueta.barra}", label: "GTIN/PLU principal" },
  { value: "${etiqueta.barraUnitario}", label: "GTIN/PLU unitário" },
  { value: "${etiqueta.codigoInternoPreco}", label: "Cód. Interno + Preço" },
  { value: "${etiqueta.curva}", label: "Curva ABC" },
  { value: "${etiqueta.data}", label: "Data alteração preço" },
  { value: "${etiqueta.dataAlteracao}", label: "Data início oferta/inclusão" },
  { value: "${etiqueta.dataEmissaoPack}", label: "Data emissão Pack" },
  { value: "${etiqueta.dataFinalPack}", label: "Data final Pack" },
  { value: "${etiqueta.dataInicialPack}", label: "Data inicial Pack" },
  { value: "${etiqueta.dataHoraImpressao}", label: "Data/Hora Impressão" },
  { value: "${etiqueta.dataOfertaFinalUnitario}", label: "Fim oferta unitária" },
  { value: "${etiqueta.dataOfertaInicialUnitario}", label: "Início oferta unitária" },
  { value: "${etiqueta.dataPrecoInicialUnitario}", label: "Data preço unitário" },
  { value: "${etiqueta.dataValidade}", label: "Data de validade" },
  { value: "${etiqueta.descricao}", label: "Descrição do Produto" },
  { value: "${etiqueta.descricaoCupom}", label: "Descrição Cupom" },
  { value: "${etiqueta.descricaoProdutoUnitario}", label: "Desc. Cupom Unitário" },
  { value: "${etiqueta.descricaoUnitario}", label: "Desc. Gôndola Unitário" },
  { value: "${etiqueta.embalagemFatorEstoqueFormatado}", label: "Unidades por embalagem" },
  { value: "${etiqueta.embalagemKey}", label: "Embalagem Key" },
  { value: "${etiqueta.estoqueDisponivel}", label: "Estoque Disponível" },
  { value: "${etiqueta.fatorEstoque}", label: "Qtd Atacado (Fator)" },
  { value: "${etiqueta.gtinPreco}", label: "GTIN + Preço" },
  { value: "${etiqueta.MarcaDescricao}", label: "Marca" },
  { value: "${etiqueta.ofertaFim}", label: "Fim da Oferta" },
  { value: "${etiqueta.ofertaInicio}", label: "Início da Oferta" },
  { value: "${etiqueta.packDescontoPercentual}", label: "Pack % Desconto" },
  { value: "${etiqueta.packDescontoUnitario}", label: "Pack Desconto R$" },
  { value: "${etiqueta.packQuantidadeDesconto}", label: "Pack Qtd Desconto" },
  { value: "${etiqueta.packQuantidadeGatilho}", label: "Pack Qtd Gatilho" },
  { value: "${etiqueta.packValorFinalUnitario}", label: "Pack Valor Final/Unit" },
  { value: "${etiqueta.packValorRateioUnitario}", label: "Pack Valor Rateio" },
  { value: "${etiqueta.packVirtualDescricao}", label: "Desc. Pack Virtual" },
  { value: "${etiqueta.packVirtualDescricaoModelo}", label: "Desc. Modelo Pack" },
  { value: "${etiqueta.packVirtualKey}", label: "Cód. Pack Virtual" },
  { value: "${etiqueta.preco}", label: "Preço de Venda" },
  { value: "${etiqueta.preco4}", label: "Preço 4 (Canal)" },
  { value: "${etiqueta.precoAtacado}", label: "Preço Atacado" },
  { value: "${etiqueta.precoAtualUnitario}", label: "Preço Atual Unitário" },
  { value: "${etiqueta.precoEspecial}", label: "Preço Especial (A partir)" },
  { value: "${etiqueta.precoNormal}", label: "Preço Normal" },
  { value: "${etiqueta.precoOferta}", label: "Preço Oferta" },
  { value: "${etiqueta.precoOfertaPorQuantidadeDaUnidadeDeMedida}", label: "Preço Oferta/Medida" },
  { value: "${etiqueta.precoOfertaFidelidade}", label: "Preço Oferta Fidelidade" },
  { value: "${etiqueta.precoPorUnidadeCaixa}", label: "Preço Unitário p/ Caixa" },
  { value: "${etiqueta.precoProdutoAtacado}", label: "Preço Prod. Atacado" },
  { value: "${etiqueta.precoProdutoAtacadoUnitario}", label: "Preço Atacado Unit." },
  { value: "${etiqueta.precoUnitario}", label: "Preço Unitário" },
  { value: "${etiqueta.precoVarejo}", label: "Preço Varejo" },
  { value: "${etiqueta.precoVendaFidelidade}", label: "Preço Venda Fidelidade" },
  { value: "${etiqueta.produtoKey}", label: "Cód. Produto" },
  { value: "${etiqueta.quantidadeApartirDe}", label: "Qtd A Partir De" },
  { value: "${etiqueta.quantidadeExposicao}", label: "Qtd Exposição" },
  { value: "${etiqueta.dataImpressao}", label: "Data Impressão (Atual)" },
  { value: "${etiqueta.packIntervaloPrimeiraQtd}", label: "Pack Intervalo 1 Qtd" },
  { value: "${etiqueta.packIntervaloPrimeiroVal}", label: "Pack Intervalo 1 Val" },
  { value: "${etiqueta.packIntervaloSegundaQtd}", label: "Pack Intervalo 2 Qtd" },
  { value: "${etiqueta.packIntervaloSegundoVal}", label: "Pack Intervalo 2 Val" },
  { value: "${etiqueta.packIntervaloTerceiraQtd}", label: "Pack Intervalo 3 Qtd" },
  { value: "${etiqueta.packIntervaloTerceiroVal}", label: "Pack Intervalo 3 Val" },
  { value: "${etiqueta.packValorComDescontoPercentual}", label: "Pack Valor c/ % Desc" },
  { value: "${etiqueta.packValorComDescontoUnitario}", label: "Pack Valor c/ Desc Un" },
  { value: "${etiqueta.tipoUnidadeMedida}", label: "Tipo Unidade Medida" },
  { value: "${etiqueta.quantidadeDaUnidadeDeMedida}", label: "Qtd Unidade Medida" },
  { value: "${etiqueta.precoPorQuantidadeDaUnidadeDeMedida}", label: "Preço p/ Qtd Medida" },
  { value: "${etiqueta.precoPorTipoUnidadeMedida}", label: "Preço p/ Tipo Medida" },
  { value: "${etiqueta.precoOfertaFidelidadePorQuantidadeDaUnidadeDeMedida}", label: "Preço Oferta Fid./Medida" },
  { value: "${etiqueta.notoriedadeProduto}", label: "Notoriedade" },
  { value: "${etiqueta.etiquetadescricaoGrade}", label: "Desc. Grade/Pai" },
  { value: "${etiqueta.temGrade}", label: "Tem Grade?" },
  { value: "${etiqueta.fabricanteProduto}", label: "CNPJ Fabricante" },
  { value: "${etiqueta.periodoOferta}", label: "Período Oferta" },
  { value: "${etiqueta.limiteQuantidadeOferta}", label: "Limite Qtd Oferta" },
  { value: "${etiqueta.limiteQuantidadeFidelidade}", label: "Limite Qtd Fidelidade" },
  { value: "${etiqueta.valorNormalEscalonamento[0]}", label: "Escalonamento Normal Val 1" },
  { value: "${etiqueta.quantidadeNormalEscalonamento[0]}", label: "Escalonamento Normal Qtd 1" },
  { value: "${etiqueta.valorOfertaEscalonamento[0]}", label: "Escalonamento Oferta Val 1" },
  { value: "${etiqueta.quantidadeOfertaEscalonamento[0]}", label: "Escalonamento Oferta Qtd 1" },
  { value: "${etiqueta.dtInicialOfertaFidelidade}", label: "Início Oferta Fidelidade" },
  { value: "${etiqueta.dtFinalOfertaFidelidade}", label: "Fim Oferta Fidelidade" },
  { value: "${etiqueta.precoPromocaoAPartirDe}", label: "Promoção A Partir De R$" },
  { value: "${etiqueta.quantidadePromocaoAPartirDe}", label: "Promoção A Partir De Qtd" },
  { value: "${etiqueta.embalagemFatorEstoquePadraoFormatado}", label: "Emb. Fator Estoque Padrão" }
];
